<enumerate object at 0x00000246B3D0F640>
DEEPMLO PiNet <function split at 0x0000024689CDEEE0>
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 147, in exc_handler
    traceback.print_exception(exc_type, exc, tb)
  File "C:\ProgramData\Anaconda3\lib\traceback.py", line 105, in print_exception
    print(line, file=file, end="")
TypeError: info() got an unexpected keyword argument 'file'
Original exception was:
Traceback (most recent call last):
  File "SmallTrainSize.py", line 360, in <module>
    train_idx = torch.tensor(all_train_idx, dtype=torch.long)
NameError: name 'all_train_idx' is not defined